save-position-on-quit=yes
watch-later-options=start
# Subtitles: always English if available
slang=en,eng,enUS,en-US
sub-auto=fuzzy
sid=auto
sub-visibility=yes
screenshot-format=png
screenshot-directory=~/Pictures/mpv
screenshot-template="%F_%tY-%tm-%td_%tH-%tM-%tS_%03n"
