#!/bin/bash

if test -e /etc/motd; then
	if ! cmp -s ${HOME}/.old_motd /etc/motd ; then
		tee ${HOME}/.old_motd < /etc/motd;
	fi
fi

echo "BASH version is $BASH_VERSION."
echo "System is `uname -a`"
echo "Term is $TERM"
echo "Shell is $SHELL"
echo "WHOAMI $USER@$HOST";
if [ -n "$SSH_CLIENT" ]; then 
	echo "Connecting from $SSH_CLIENT"
fi
if [ -n "$DISPLAY" ]; then 
	echo "Dispaly is set ${DISPLAY}"
fi

# SSH Agent if required
