#!/bin/bash

{{ $shell = "bash" }}

{{ template "shell-login-common.tmpl" merge $ (dict "shell" $shell) }}

# From https://github.com/jordansissel/dotfiles/blob/master/.bash_profile
# Exec zsh if it exists.
if test -x `which zsh`; then  
	echo "zsh found on system "
else
	echo "No zsh found, sorry I couldn't save you..."
fi

# SSH Agent if required
