#!/bin/bash

# History options
export HISTSIZE=99999
export HISTFILE=$HOME/.bash_history
export SAVEHIST=99999
export HISTFILESIZE=99999






# Key bindings
set -o vi
bind '"^R":"history-incremental-search-backward"'


# Shell stuff
export PS1='${PWD}
\u@\h \!\$ '

##uncomment the following to activate bash-completion:
#[ -f /etc/profile.d/bash-completion ] && source /etc/profile.d/bash-completion

# TODO Machine specifix
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*


