name: Package Dotfiles

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Apply configuration
        run: |
          yes "" | sh -c "$(curl -fsLS get.chezmoi.io)" -- init --no-tty --debug --source=$PWD --apply
      - name: Create archive
        run: |
          ./bin/chezmoi archive --source=$PWD --format zip --output dotfiles.zip
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dotfiles.zip
