name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - run: |
          shopt -s globstar
          shellcheck **/*.sh
      - run: |
          yes "" | sh -c "$(curl -fsLS get.chezmoi.io)" -- init --no-tty --debug --apply arran4
